# docker-compose -f  konumAdi/docker-compose.yml up -d
# docker stop $(docker ps -qa)
version: '3.1'

services:

  #  jenkins
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - '7777:8080'
      - '50000:50000'
    container_name: jenkins
    volumes:
      - /home/${myname}/jenkins_compose/jenkins_configuration:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

  # cassandra
  cassandra:
    image: cassandra
    ports:
      - '9042:9042'

#  mysql:
#    image: mysql
#    restart: always
#    environment:
#      MYSQL_ROOT_PASSWORD: 123456
#    ports:
#      - '3306:3306'

  # elasticsearch
  elasticsearch:
    image: elasticsearch:7.5.0
    ports:
      - '9200:9200'
      - '9300:9300'
    environment:
      discovery.type: single-node