# Dikkat: account-service projesiyle account-service.yml aynı isimde olması gerekiyor

server:
  port: 8501

# application name
spring:
  application:
    name: account-service

  # zipkin application seviyesinde
  zipkin:
    base-url:http//localhost:9411/

# cassandra çalışması için
spcloud:
  cassandra:
    contact:
      point: 127.0.0.1
    port : 9042
    keyspace:
      name: pachysandra
    username : cassandra
    password : cassandra


# eureka haberder olması icin
eureka:
  client:
    instance:
      hostname: localhost
    serviceUrl:
      defaultZone: http://localhost:8500/eureka/

